apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: redisconnect
  name: redisconnect
  namespace: open-cluster-management
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: redisconnect
    spec:
      volumes:
      - name: search-certs
        secret:
          secretName: search-aggregator-certs
      - name: redis-graph-certs
        configMap:
          name: search-ca-crt
          items:
          - key: service-ca.crt
            path: redis.crt
      containers:
      - image: quay.io/sherinv/redisconnect:latest
        imagePullPolicy: Always
        name: redisconnect
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REDIS_SSH_PORT
          value: "6380"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redisgraph-user-secret
              key: redispwd     
        livenessProbe:
          httpGet:
            path: /liveness
            port: 3010
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3010
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - name: search-certs
          mountPath: /sslcert
        - name: redis-graph-certs
          mountPath: /rediscert/redis.crt
          subPath: redis.crt
      hostIPC: false
      hostNetwork: false
      hostPID: false
      imagePullSecrets:
      - name: multiclusterhub-operator-pull-secret
      serviceAccount: search-collector
      serviceAccountName: search-collector
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30